CREATE TABLE IF NOT EXISTS Members(
    Mem_ID TEXT NOT NULL PRIMARY KEY,
    Mem_Name TEXT NOT NULL,
    MEM_DOB INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Competitions(
    Comp_ID TEXT NOT NULL PRIMARY KEY,
    Comp_Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Scores(
    Mem_ID TEXT NOT NULL REFERENCES Members(Mem_ID),
    Comp_ID TEXT NOT NULL REFERENCES Competitions(Comp_ID),
    Comp_Score INTEGER NOT NULL,
    PRIMARY KEY (Mem_ID,Comp_ID)
);